### ISSUE TITLE
Fix the security issue reported by Bitdefender for certain readers of the blog on mobile

### ISSUE THREAD

**Issue by dassiorleando** [numerica-ideas/community#25]
![D0CB4B04-DA73-4145-8958-23412C79E3A0](https://user-images.githubusercontent.com/7150752/224865703-7dae2a37-11ec-46df-a78b-d850902fb4d4.jpeg)

**Comment by kemanedonfack** [comment]
<img width="640" alt="Capture d’écran 2023-06-04 170343" src="https://github.com/numerica-ideas/community/assets/70517765/c55a4b0e-7529-4905-88b0-3ca2d36cce38">

**Comment by dassiorleando** [comment]
I just submitted a request to Bitdefender in order to remove the security detection for **Numerica Ideas** since it's 100% legit with no malware in it, I hope it's going to be solved soon.

Form: https://www.bitdefender.com/consumer/support/answer/29358/

<img width="1709" alt="Screenshot 2024-01-20 at 14 53 44" src="https://github.com/numerica-ideas/community/assets/7150752/dfc2b17b-c174-4100-b6ef-13346526d977">

**Comment by dassiorleando** [comment]
**Finally, it's all green as per the last Bitdefender checks today.**

Thanks to @sylvinkamdem for reporting this and conducted numerous tests during months of clearing this **false positive**.

<img width="1397" alt="Screenshot 2024-03-06 at 06 13 15" src="https://github.com/numerica-ideas/community/assets/7150752/d860c318-bc46-464b-ac49-a9435f0a46ab">

**Comment by Sylvinkamdem** [comment]
Congratulations for your hard work. Keep pushing forward.
