### ISSUE TITLE
Bring back the "Algorithmic Challenge" activity (FR)

### ISSUE THREAD

**Issue by dassiorleando** [numerica-ideas/community#27]
### Context
Setup and bring back the algorithm activity that we were doing on Skype, but now at the community level in the Discord server.

### Goal
One algorithm exercise per week as we used to.

**Comment by messaismael** [comment]
Hi @dassiorleando 
That is great! 
Since we used to do it on skype together, can I handle this activity for the community on the Discord server? 📈

**Comment by dassiorleando** [comment]
@messaismael
Yes please, feel free to go wild on that 💯

**Comment by messaismael** [comment]
Fine, thank you! 👍🏽 
I'll do my best.

**Comment by dassiorleando** [comment]
@messaismael anything new on this thread?
This is going to be a French activity, right? If YES, let's handle everything in french **from day 0** 😃

**Comment by dassiorleando** [comment]
Je ferme cette tâche étant donné qu'elle est maintenant gérée par @messaismael, les sessions de challenges auront lieu chaque Samedi à [14h UTC](https://www.timeanddate.com/time/zone/timezone/utc) et ce en Français.

![Challenge Algorithmique](https://user-images.githubusercontent.com/7150752/227078449-adfab18f-87c7-4378-a31c-51c0958e1dc9.png)

**Note**: n'hésitez pas de créer une activité pareille pour l'Anglais si vous serez en mesure de leader cela.
